> **Student Names and IDs**:
> - Pablo Ortiz, 0686443
> - Jongwan Park, 0848815

# Homework 4

## Part 1: Exam-Style Questions

### Problem 1.1

Suppose that the histogram of orientations $\theta\in [0, 180)$ has 18 equal bins, numbered 0 to 17, and with centers $5, 15, \ldots, 175$. Bilinear voting is used, as described in the class notes on Histograms of Oriented Gradients. Give the fraction of vote that each of the bins receives when a measurement $\theta = 42$ is observed. Fractions are values in $[0, 1]$.

### Answer

For bin 3:

$$
(45 - 42)/10 = 0.3
$$

For bin 4:

$$
(42 - 35)/10 = 0.7
$$

Rest of the bins:

$$
0
$$

### Problem 1.2

The $x$ and $y$ components of $\nabla I$ at a particular pixel in an image are $10\sqrt{3}$ and $10$, respectively. What are the magnitude and orientation of the gradient there? Express orientation in degrees relative to the $x$ axis.

### Answer

Magnitude:
$$
\mu = \sqrt{I_x^2 + I_y^2} = \sqrt{300 + 100} = 20
$$

Orientation:
$$
\theta = \frac{180}{\pi} \left(\arctan\left(\frac{I_y}{I_x}\right)\mod \pi\right) = \frac{180}{\pi} \left(\arctan\left(\frac{10}{10\sqrt{3}}\right)\mod \pi\right) = 30°
$$

### Problem 1.3

A HOG feature is computed from a $128\times 64$ window divided into cells with $8\times 8$ pixels each. The size of a block is $2\times 2$ cells. Central differences are used to compute gradients. Each cell histogram has nine bins of equal size, and bin 0 is for orientations in $[0, 20)$ degrees.

Rather than using a constant $\epsilon$ in the denominator during normalization of a histogram $\mathbf{v}$, the following procedure is used at all stages to normalize a histogram $\mathbf{v}$ to $\mathbf{v}'$:

$$
\mathbf{v'} \;=\; \left\{\begin{array}{ll} \frac{\mathbf{v}}{\|\mathbf{v}\|} &
\mbox{if $\|\mathbf{v}\| \neq 0$} \\ \mathbf{v} & \mbox{otherwise.}\end{array}\right.
$$

The threshold $\tau$ used to saturate the feature entries during contrast normalization is set to infinity (so that it has no effect).

For a given window, the pixel at position $(5, 5)$ has value 50, and all other pixels are zero.

Give an expression for the entries of the HOG feature $\mathbf{h}$ for that window.

### Answer

Only cell (0,0) (thus block (0,0)) contains the nonzero pixel.
Computing $\nabla I$...

For (5,4), (5,6), 

$$
I_x = 50, I_y = 0.\\
\theta = 0.
$$

=> bin 0 and 8 get 1 vote each (50).

For (4,5), (6,5),

$$
I_x = 0, I_y = 50.\\
\theta = 90°.
$$

=> bin 4 gets 2 votes (2*50 = 100).

For the block (0,0), $\mathbf{b}_0$, whose length is 36,

$$
\mathbf{b}_0 [0] = 50,\\
\mathbf{b}_0 [4] = 100,\\
\mathbf{b}_0 [8] = 50.
$$

Normalizing it gives,

$$
\tilde{\mathbf{b}}_0 [0] = 1/\sqrt{6},\\
\tilde{\mathbf{b}}_0 [4] = 2/\sqrt{6},\\
\tilde{\mathbf{b}}_0 [8] = 1/\sqrt{6}.
$$

Concatenating all the 15x7 blocks result in $\mathbf{h}$ with the length of 3780.

$$
\mathbf{h} [0] = 1/\sqrt{6},\\
\mathbf{h} [4] = 2/\sqrt{6},\\
\mathbf{h} [8] = 1/\sqrt{6}.
$$

As $\mathbf{b}$ was already nonrmalized and all the other entries of $\mathbf{h}$ are 0, there is no need to normalize $\mathbf{h}$.

### Problem 1.4

The magnitude of a vector $\mathbf{x} = [x, y]^T\in\mathbb{R}^2$ is

$$
            f(x, y) = \sqrt{x^2 + y^2}\;.
$$

Write algebraic expressions and exact decimal numerical values of the gradient $\nabla f$ and Hessian $H_f$ of $f$ at $x=3$ and $y=4$.

[Hint: $1/5^3 = 1/125 = 8/1000$.]

### Answer

Calculating gradient:

$$
\nabla f(x,y) =\frac{\partial f}{\partial x} + \frac{\partial f}{\partial y} =\frac{x}{\sqrt{x^2+y^2}} + \frac{y}{\sqrt{x^2+y^2}},\\
\nabla f (3,4) = \frac{3}{5} + \frac{4}{5} = \frac{7}{5} = 1.4 \;.
$$

Calculating Hessian $H_f$:

$$
H_f(\mathbf{x}) =
\frac{\partial^2 f}{\partial \mathbf{x} \partial \mathbf{x}^T} =
\left[\begin{array}{cc}
\frac{\partial^2 f}{\partial x^2} &
\frac{\partial^2 f}{\partial x \partial y}\\
\frac{\partial^2 f}{\partial y \partial x} &
\frac{\partial^2 f}{\partial y^2} \end{array} \right]\\
= 
\left[\begin{array}{cc}
\frac{1}{\sqrt{x^2+y^2}} -\frac{x^2}{(x^2+y^2)^{3/2}} &
-\frac{xy}{(x^2+y^2)^{3/2}} \\
-\frac{xy}{(x^2+y^2)^{3/2}} &
\frac{1}{\sqrt{x^2+y^2}} -\frac{y^2}{(x^2+y^2)^{3/2}} \end{array} \right]\\
$$

$$
H_f (3,4) = \left[\begin{array}{cc}
\frac{1}{5}-\frac{9}{125} &
-\frac{12}{125} \\
-\frac{12}{125} &
\frac{1}{5}-\frac{16}{125} \end{array} \right]\\
= \left[\begin{array}{cc}
\frac{16}{125} &
-\frac{12}{125} \\
-\frac{12}{125} &
\frac{9}{125} \end{array} \right]\\
= \left[\begin{array}{cc}
0.128 &
-0.096 \\
-0.096 &
0.072 \end{array} \right].\\
$$

### Problem 1.5

The second stage of line search repeatedly narrows a bracketing triple $(a, b, c)$ established in the first stage. Suppose that at some point during the second stage the bracketing triple is:

$$
a = 0 \;\;\;,\;\;\; b = 2 \;\;\;,\;\;\; c = 6
$$

with function values

$$
h(a) = 6 \;\;\;,\;\;\; h(b) = 3 \;\;\;,\;\;\; h(c) = 4
$$

along the search line. Assume further that

$$
h(1) = 2 \;\;\;\text{and}\;\;\; h(4) = 5\;.
$$

What is the bracketing triple after that? Standard line search is applied, that is, no golden ratio is used. No need to explain.

[Hint: Draw a sketch.]

### Answer

The bracketing triple after that is (0, 1, 2)

### Problem 1.6

The gradient and Hessian at $\mathbf{z}_0 = [4, 1]^T$ for some function $f\ :\ \mathbb{R}^2 \rightarrow \mathbb{R}$ are as follows:

$$
\nabla f(\mathbf{z}_0) \;=\; \left[\begin{array}{c}2\\1 \end{array}\right]
\;\;\;\text{and}\;\;\;
H_f(\mathbf{z}_0) \;=\; \left[\begin{array}{c}2 & 1\\1 & 3 \end{array}\right] \;.
$$

Find the point $\mathbf{z}_1$ that results by taking a single Newton step from $\mathbf{z}_0$. Show your reasoning briefly.

### Answer

To find $\mathbf{z}_1$, we must solve $H_f(\mathbf{z}_0)\Delta \mathbf{z} = -\nabla f(\mathbf{z}_0)$, where $\Delta \mathbf{z}=\mathbf{z}_1 - \mathbf{z}_0$, 

$\left[\begin{array}{cc} 2&1\\ 1&3 \end{array}\right] \Delta{z} = -\left[\begin{array}{c} 2\\ 1 \end{array}\right]$

We could solve this by inverting the $H_f(\mathbf{z}_0)$, but from simle observation it can be seen that 
$$
\Delta \mathbf{z} = \left[\begin{array}{c} -1\\ 0 \end{array}\right]
$$
solves the equation

We can now find the point $$\mathbf{z_1}=\mathbf{z_0} + \Delta \mathbf{z}=\left[\begin{array}{c} 4\\ 1 \end{array}\right]+\left[\begin{array}{c} -1\\ 0 \end{array}\right] = \left[\begin{array}{c} 3\\ 1 \end{array}\right]$$

### Problem 1.7

A classification problem asks to find a classifier $h\in\mathcal{H}$ whose domain $X$ and co-domain $Y$ of $h$ are defined as follows:

$$
X = \{0, 2, 4, 6, 8, 10\} \;\;\;\text{and}\;\;\; Y = \{0, 1\}
$$

and the hypothesis space $\mathcal{H}$ is the set of the following five functions

$$
h_k(x) = \left\{\begin{array}{ll}0 & \mbox{if $x < k$}\\
1 & \mbox{otherwise}\end{array}\right.
\;\;\;\text{for}\;\;\; k = 1, 3, 5, 7, 9\;.
$$

The following tiny training set is given:

$$
T = \{(0, 0), (2, 0), (4, 1), (6, 1) \} \;.
$$

Make a table of the training risk $L_T(h_k)$ for $k = 1, 3, 5, 7, 9$.  Express values in percent. Then use the table to determine the optimal classifier $\hat{h}$ for this training set (thus, we only care about empirical risk here).

### Answer

$$
\begin{array}{r|ccccc}
k & 1 & 3 & 5 & 7 & 9 \\\hline
L_T(h_k) & 1/4 & 0 & 1/4 & 1/2 & 1/2 
\end{array}
$$

The optimal classifier on $T$ is $\hat{k} = 3$.

### Problem 1.8

Assume that the probability model $p(x, y)$ for the data in Problem 1.7 is as specified in the table below. The table contains the joint probability $p(x, y)$ with values expressed in percent, rather than as numbers in $[0, 1]$. It has one column per value of $x$ and one row per value of $y$.

$$
\begin{array}{c|ccccccc}
 & 0 & 2 & 4 & 6 & 8 & 10 \\\hline
0 & 12 & 11 & 10 & 7 & 6 & 4 \\
1 & 2 & 4 & 6 & 10 & 12 & 16
\end{array}
$$

Under the same circumstances as in Problem 1.7, and with the probability model above, make a table of the statistical risk $L_p(h)$ and determine the classifier that generalizes best. Express values in percent.

### Answer

$$
\begin{array}{r|ccccc}
k & 1 & 3 & 5 & 7 & 9 \\\hline
L_p(h_k) & 40 & 33 & 29 & 32 & 38 
\end{array}
$$

The classifier that generalizes best is $\hat{k} = 5$.

## Part 2: Projections

### Problem 2.1

What is the shape (number of rows and columns) of $U$? Explain briefly.

### Answer

The shape of $U$ is (Rows: m, Columns: m-1). 

Columns: The number of Columns is simply the number of basis vectors of $\mathcal{O}(u)$. Since $\mathcal{O}(u)$ is a subset of $\mathbb{R}^m$, it cannot have more than m basis vectors. Note that the basis vectors of $\mathcal{O}(u)$, together with $\mathbf{b}$, by definition span $\mathbb{R}^m$. And since we know $\mathbb{R}$ is m-dimensional, we know it can be spanned by no fewer than m vectors. Since one of these is $\mathbb{b}$, we conclude that there are m-1 other vectors, and since these span $\mathcal{O}(u)$, then that matches the number of columns of $U$.

Rows: The number of Rows is simply the dimensionality of each of the basis vectors. Since it is defined that 'the space $\mathcal{O}(u)$ is the set of all vectors in $\mathcal{R}^m$...' we know the basis vectors must have exactly dimensionality of m.

### Problem 2.2

Explain clearly how, given $\mathbf{u}$, you can use the Singular Value Decomposition (SVD) to compute a matrix whose columns form an orthonormal basis for $\mathcal{O}(\mathbf{u})$. Also explain why.

Then show a basis for $\mathcal{O}([1, 1, 0]^T)$ using your technique.

Give the projection matrix $P$ for this space, and the projection of the vector $\mathbf{b} = [0, 2, -4]^T$ onto $\mathcal{O}([1, 1, 0]^T)$.

Use whatever code you'd like, but do **not** submit your code. Give your numerical results either exactly (if you can guess what they are) or with four decimal digits after the period.

Do **not** use any other techniques, such as Gram-Schmidt.

### Answer

We can take advantage of the SVD to find an orthonormal basis of $\mathcal{O}(u)$. The method I am going to use is simple. For a given $u$ of shape m by 1:


#### First:

Construct a m by m+1 matrix A whose first column is $u$ and the the rest of its columns are the columns of $I_m$.

For example, if m=3 and $u = [2, 3, 4]^T$, 
$$
A = \left[\begin{array}{ccc}2 & 1 & 0 & 0\\3 & 0 & 1 & 0\\4 & 0 & 0 & 1 \end{array}\right]
$$

* We realized later this same process could be done without actually appending the identity (aka, simply making A = u). 

#### Second: 

Find the SVD of A and store matrix U.

#### Third: 

Remove the first column of U, and then you are done. The remaining matrix is the m by m-1 matrix with columns that form an orthonormal basis of $\mathcal{O}(u)$, as asked.

#### Why it works:

First notice that 
1. the columns of A span $\mathbb{R}^m$ (notice it actually does so reduntantly since it has m+1 columns in m dimensional space, but that doesn't matter because they're not a basis). 

Because of that, there must exist a subset of them that also spans $\mathbb{R}^m$. In constructing the U matrix from the svd, we note that 
2. every element of U is unitary, (from the definition of SVD)
3. every column of U is orthogonal to each other (from the definition of SVD)

An important conclusion from these three facts is that: if one of the columns of U is parallel to $u$, then the others must be an orthonormal basis of $\mathcal{O}(u)$ (since they are unitary, orthogonal to $u$, to each other, and span the correct space)

This means I need to prove that the first column of U is parallel to $u$ and my proof is complete: 

Since the column space of A and U is the same, the first column of U must correspond to a normalized version of the first column of A, which is $u$, completeing the proof of the algorithm.

#### Show a Basis of $\mathcal{O}([1,1,0]^T)$ using this technique (without showing the code):

$([0,\ 0,\ 1]^T, \ \ \ \ [-0.7071,\ 0.7071,\ 0]^T)$. In this case it's an orthonormal one.

The Projection matrix can computed by $P=UU^T$, where $U$ is a matrix whose columns are the mentioned orthonormal basis vectors:
$$U = \left[\begin{array}{cc} 0 & -\sqrt{2}\ /2\\ 0&\sqrt{2}\ /2\\ 1&0\end{array}\right]$$


$$P = \left[\begin{array}{ccc} 1/2 & -1/2 & 0\\ -1/2&1/2&0\\ 0&0&1\end{array}\right]$$

$$p=Pb = \left[\begin{array}{ccc} 1/2 & -1/2 & 0\\ -1/2&1/2&0\\ 0&0&1\end{array}\right] \left[\begin{array}{c} 0\\ 2\\ -4\end{array}\right]=\left[\begin{array}{c} -1\\ 1\\ -4\end{array}\right]$$

### Problem 2.3

For each of the two matrices $U$ and $P$ and the vector $\mathbf{p}$ you found in the previous problem, state whether the object is unique, and explain briefly why or why not.

### Answer

U: NOT unique
U is not unique for two reasons. 
1. The orthonormal basis vectors would still serve as valid orthonormal basis vectors if negated. For example, [1, 0, 0] and [-1, 0, 0] are both valid unitary vectors that span the same subspace. 
2. The order of permutation of the columns can vary.

P: YES unique
Despite $U$ not being unique, $P$ is. That is because when multiplying $U$ by $U^T$, the two previous reasons get eliminated:
1. Whether or not a vector was negated, does not matter since their elements will get multiplied to each other, meaning that if they're both negated, their product will not be. 
2. In matrix multiplication, the permutation of columns translates to a permutation in addition of columns. But since addition is commutative, it does not make a difference in P.

p: YES unique

Since b and P are unique, their matrix multiplication is also unique.

### Problem 2.4

Compute the matrix $$Q = I - \mathbf{n}\mathbf{n}^T$$ for the example given in Problem 2.2.

Show $Q$ if it is different from the matrix $P$ you obtained through SVD. Otherwise, just state that the two matrices are the same.

### Answer

The two matrices are the same

## Part 3: Optimization and the SVD

In [15]:
import numpy as np
from scipy.optimize import minimize_scalar

def normalize(v):
    n = np.linalg.norm(v)
    if n > 0:
        v = v / n
    return v, n

# sphere_search returns a new point z1, not a search step size
def sphere_step(f, g, z0, epsilon=1.e-6, args=()):
    assert epsilon > 0 and epsilon < 1, 'epsilon must be in (0, 1)'
    assert z0.size > 1, 'sphere must be at least 2-dimensional'
    
    n0, delta = 0, 0
    while n0 < epsilon:
        z0 += delta * np.sqrt(epsilon) * np.random.random(z0.shape)
        z0, _ = normalize(z0)
        p0 = -g(z0, *args)  # Starting direction
        
        # Project p0 onto the tangent hyperplane to the sphere at z0 and normalize
        s0, n0 = normalize(p0 - np.dot(z0, p0) * z0)
        delta = 1
    
    def h(theta, args):
        return f(z0 * np.cos(theta) + s0 * np.sin(theta), args)
    
    res = minimize_scalar(h, bracket=(0, 1), args=args)
    theta = res.x
    return z0 * np.cos(theta) + s0 * np.sin(theta)

### Problem 3.1

Write a function with the following header and `assert` statements:

    def first(A, epsilon=1.e-6, maxiter=10):
        assert A.size > 0, 'array cannot be empty'
        assert np.max(np.abs(A)) >= epsilon, 'array cannot be zero'

that uses `sphere_step` iteratively to return the tuple `u, sigma, v` of the first left singular vector, first singular value, and first right singular vector of `A`.

Show your code and the results of running the given tests. You may want to compare your results with those obtained with an off-the-shelf implementation of the SVD. However, do **not** submit your comparison, and do not use SVDs anywhere in your code.

### Answer

In [113]:
def first(A, epsilon=1.e-6, maxiter=10):
    assert A.size > 0, 'array cannot be empty'
    assert np.max(np.abs(A)) >= epsilon, 'array cannot be zero'
    
    def f(u, A):
        return -np.linalg.norm(np.matmul(A,u))**2

    def g(u, A):
        return -2*np.matmul(A.T, np.matmul(A,u))
    
    if np.min(A.shape) < 2:
        if A.shape[0] == 1:
            sigma = np.linalg.norm(A)
            u = np.zeros(1)
            u[0] = 1
            v = np.squeeze(A/sigma)
        else:
            sigma = np.linalg.norm(A)
            v = np.zeros(1)
            v[0] = 1
            u = np.squeeze(A/sigma)
    else:
        v_old = np.zeros(A.shape[1])
        diff = epsilon + 1
        while diff > epsilon:
            v_new = sphere_step(f, g, v_old, epsilon=1.e-6, args=(A,))
            diff = np.linalg.norm(v_new - v_old)
            v_old = v_new
        
        v = v_new
        sigma = np.linalg.norm(np.matmul(A,v))
        u = np.matmul(A,v)/sigma
    
    return (u, sigma, v)
        


In [114]:
def test(f, A_list):
    def printArray(name, A):
        print(name, A, sep='\n', end='\n\n')
        
    if f.__name__ is 'first':
        un, sn, vn = 'u', 'sigma', 'v'
        product = False
    else:
        un, sn, vn = 'U', 'Sigma', 'V'
        product = True

    np.set_printoptions(precision=4, suppress=True)
    
    for A in A_list:
        U, Sigma, V = f(A)
        print('=' * 10, 'testing', f.__name__, '=' * 10)
        printArray('A', A)
        if product:
            printArray("U * Sigma * V'", np.dot(U, np.dot(Sigma, V.T)))
        printArray(un, U)
        printArray(sn, Sigma)
        printArray(vn, V)
        
        print('=' * 5, 'using numpy SVD function', '=' * 5)
        U_real, Sigma_real, V_real = np.linalg.svd(A)
        if product:
            printArray(un, U_real)
            printArray(sn, Sigma_real)
            printArray(vn, V_real)
        else:
            printArray(un, U_real[:,0])
            printArray(sn, Sigma_real[0])
            printArray(vn, V_real[:,0])
s3 = np.sqrt(3)
A_list = (np.array([[s3, s3], [-3., 3.], [1., 1.]]) / np.sqrt(2.),
          np.outer([1., 2., 3.], [2., 0., -1., 3.]),
          np.array([[3.], [0.], [4.]]), np.array([[4., -3.]]))

# try:
#     test(first, A_list)
# except NameError:
#     pass
test(first, A_list)


========== testing first ==========
A
[[ 1.2247  1.2247]
 [-2.1213  2.1213]
 [ 0.7071  0.7071]]

u
[ 0. -1.  0.]

sigma
3.0

v
[ 0.7071 -0.7071]

===== using numpy SVD function =====
u
[-0.  1. -0.]

sigma
2.9999999999999996

v
[-0.7071 -0.7071]

========== testing first ==========
A
[[ 2.  0. -1.  3.]
 [ 4.  0. -2.  6.]
 [ 6.  0. -3.  9.]]

u
[0.2673 0.5345 0.8018]

sigma
14.000000000000002

v
[ 0.5345  0.     -0.2673  0.8018]

===== using numpy SVD function =====
u
[-0.2673 -0.5345 -0.8018]

sigma
14.0

v
[-0.5345  0.2673  0.     -0.8018]

========== testing first ==========
A
[[3.]
 [0.]
 [4.]]

u
[0.6 0.  0.8]

sigma
5.0

v
[1.]

===== using numpy SVD function =====
u
[0.6 0.  0.8]

sigma
5.0

v
[1.]

========== testing first ==========
A
[[ 4. -3.]]

u
[1.]

sigma
5.0

v
[ 0.8 -0.6]

===== using numpy SVD function =====
u
[-1.]

sigma
5.0

v
[-0.8  0.6]



### Problem 3.2

Use your function `first` to write a function with the following header and `assert` statement that computes the "tiny" SVD of a non-empty matrix $A$, with the given specifications:

    def SVD(A, epsilon=1.e-3, maxiter=10):
        assert A.size > 0, 'array cannot be empty'
        
The function should return the tuple `U, Sigma, V` of the matrices in the "tiny" SVD of `A`, and should comply with the programming notes.
        
Show your code and the results of running the given tests. You may want to compare your results with those obtained with an off-the-shelf implementation of the SVD. However, do **not** submit your comparison. Do not use library SVDs anywhere in your code.

### Answer

In [119]:
def SVD(A, epsilon=1.e-3, maxiter=10):
    assert A.size > 0, 'array cannot be empty'
    
    A_new = A
    
    U1 = np.zeros(A.shape[0])[:,np.newaxis]
    V1 = np.zeros(A.shape[1])[:,np.newaxis]
    Sigma1 = np.zeros(1)[np.newaxis]
    
    while np.max(np.abs(A_new)) > epsilon:
        sigma = np.zeros(1)
        u, sigma_, v = first(A_new)
        sigma[0] = sigma_
        U1 = np.concatenate((U1,u[:,np.newaxis]), axis=1)
        V1 = np.concatenate((V1,v[:,np.newaxis]), axis=1)
        Sigma1 = np.append(Sigma1,sigma_)
        A_old = A_new
        
        v = v[:,np.newaxis]
        A_new = A_old - ( np.matmul(A_old, np.matmul(v,v.T)) )
    
    U = U1[:, 1:]
    V = V1[:, 1:]
    Sigma = np.diag(Sigma1[1:])
    
    return (U, Sigma, V)

In [2]:
s3 = np.sqrt(3)
A_list = (np.array([[s3, s3], [-3., 3.], [1., 1.]]) / np.sqrt(2.),
          np.outer([1., 2., 3.], [2., 0., -1., 3.]),
          np.array([[3.], [0.], [4.]]), np.array([[4., -3.]]))

# try:
#     test(SVD, A_list)
# except NameError:
#     pass

test(SVD, A_list)


NameError: name 'np' is not defined